name: Build Host Binaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./host
        run: npm install

      - name: Copy Client directory for packaging (Unix)
        run: cp -r client host/client_dist
        if: runner.os != 'Windows'

      - name: Copy Client directory for packaging (Windows)
        run: xcopy client host\client_dist /E /I /Y
        if: runner.os == 'Windows'

      - name: Build Binary
        working-directory: ./host
        run: npx electron-builder

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HealingNodes-Executables-${{ matrix.os }}
          path: |
            host/dist/*.exe
            host/dist/*.AppImage
            host/dist/*.dmg
            host/dist/*.zip
            host/dist/*.tar.gz
